services:
  metronome-web:
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    command: node build
    ports:
      - '3002:3002'
    environment:
      NODE_ENV: develop
      HOST: 0.0.0.0
      PORT: 3002
